version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8000:80"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "8080:80"

# Construção e execução dos containers:
# docker build -t backend .
# docker run -p 8000:80 backend

# docker build -t frontend_vue .
# docker run -p 8080:80 frontend_vue
