version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8080:80"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "4200:80"

  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"
