FROM node:14 AS build-stage
WORKDIR /app
COPY /frontend_vue/package*.json ./
RUN npm install
COPY /frontend_vue /app
RUN npm run build

# Estágio 2
FROM nginx:alpine AS production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
