FROM node:18 AS angular-builder

WORKDIR /app

COPY frontend /app

RUN npm install
RUN npm run build --prod

FROM nginx:alpine

COPY --from=angular-builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
